### 유저 생성
POST localhost:8081/api/accounts/users
Content-Type: application/json

{
  "userId": "test",
  "email": "test@naver.com",
  "password": "1234"
}

### 유저 생성2
POST localhost:8081/api/accounts/users
Content-Type: application/json

{
  "userId": "test2",
  "email": "test2@gmail.com",
  "password": "5678"
}

### 전체 유저 조회
GET http://localhost:8081/api/accounts/users
Accept: application/json

### 단일 유저 조회
GET http://localhost:8081/api/accounts/users/test

### 유저 업데이트
POST http://localhost:8081/api/accounts/users/test
Content-Type: application/json

{
  "email": "modified@naver.com",
  "password": 1234
}

### 유저 탈퇴
POST localhost:8081/api/accounts/users/test

### 로그인
POST http://localhost:8081/api/accounts/login
Content-Type: application/json
Accept: application/json

{
  "userId":"test",
  "password": "1234"
}


### test
GET localhost:8081/api/account/users/test/exists
Conten