spring.application.name=mini-dooray
spring.mvc.hiddenmethod.filter.enabled=true

server.port=8080

api.gateway.url=http://localhost:8000
api.account.url=${api.gateway.url}/api/accounts
api.task.url=${api.gateway.url}/api/tasks
